# Generated by Django 3.0.4 on 2020-03-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='base65_image',
            new_name='base64_image',
        ),
    ]
